"""Add users.

Revision ID: 1ce7873ac4ced2
Revises: 
Create Date: 2023-06-18 15:00:32.799885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce7873ac4ced2'
down_revision = '1b45aaa4b20d'
branch_labels = None
depends_on = '1b45aaa4b20d'


def upgrade():
    op.execute("""INSERT INTO "user" VALUES (1, 'admin', '2d58b0ac72f929ca9ad3238ade9eab69', 'admin');""")
    op.execute("""INSERT INTO "user" VALUES (2, 'julius', '4024fb06e1423da90b80f0274e8e4476', 'user');""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
